-- lleno la tabla de usuarios:
INSERT INTO USERS (USER_ID, USER_NAME, USER_TYPE) VALUES (1, 'USER1', 'COMMON');
INSERT INTO USERS (USER_ID, USER_NAME, USER_TYPE) VALUES (2, 'USER2', 'COMMON');
INSERT INTO USERS (USER_ID, USER_NAME, USER_TYPE) VALUES (3, 'USER3', 'COMMON');
INSERT INTO USERS (USER_ID, USER_NAME, USER_TYPE) VALUES (4, 'Grupo del Trabajo', 'GROUP');

-- lleno la tabla de contactos:

-- Contactos USER1 : USER2, USER3, USER4
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (1, 1, 2);
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (2, 1, 3);
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (3, 1, 4);

-- Contactos USER2: Grupo del Trabajo.
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (4, 2, 4);

-- Contactos USER3: USER1 y Grupo del Trabajo.
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (5, 3, 1);
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (6, 3, 4);

-- Contactos USER4: USER1, USER2 Y USER3.
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (7, 4, 1);
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (8, 4, 2);
INSERT INTO CONTACTS (CONTACT_ID, USER_ID, CONTACT_USER_ID) VALUES (9, 4, 3);
